// ##########################################################################
// ### This file is generated by Build and Continuous Integration scripts ###
// ###   .github/workflows/buildinfo.py for local development environment ###
// ###   .github/workflows/testbuildrelease.yml for CI environment        ###
// ### Changes will be overwritten on the next build                      ###
// ##########################################################################

#include <buildinfo.hpp>

const buildEnvironment buildInfo::theBuildEnvironment{buildEnvironment::local};
const buildType buildInfo::theBuildType{buildType::development};
const int buildInfo::mainVersionDigit   = 0;
const int buildInfo::minorVersionDigit  = 1;
const int buildInfo::patchVersionDigit  = 0;
const char* buildInfo::lastCommitTag    = "defaf7b";
const char* buildInfo::buildTimeStamp   = "2024-Feb-29 11:11:37";
